---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# auto.template.creation

<!-- badges: start -->
<!-- badges: end -->

The goal of auto.template.creation is to automate the process of generating analytics-lab ready templates with set AccNR and ProvID.

## Modules and Structure

### Modules

* login
** Test
* user_management
* project_management
* lab_management
* project_selector
* samples_preparation
* set\_accnr\_and\_provid
* export

### Functions
* generate_template
* sqlite

### Utils
* long\_and\_wide\_prover
* accnr_helpers
* provid_helpers

### Module Structure

```
ui/server
└── login
    ├── user_management
    ├── project_management
    │   └── project_selector
    └── lab_management
        ├── project_selector
        ├── samples_preparation
        │   └── set_accnr_and_provid
        └── export
```

## Installation

You can install the development version of auto.template.creation from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("mskoldSU/lab_templates")
```

### Running development version

The server can be started for development using the run_dev.R script in the `/dev` folder.
``` bash
Rscript dev/run_dev.R
```

### Deploying

To deploy run 
``` bash
Rscript dev/03_deploy.R
```

## Build README

You'll need to render `README.Rmd` regularly, to keep `README.md` up-to-date. `devtools::build_readme()` is handy for this. You could also use GitHub Actions to re-render `README.Rmd` every time you push. An example workflow can be found here: <https://github.com/r-lib/actions/tree/v1/examples>.
